#!/bin/bash

BASE_DIR="/var/lib/univention-appcenter/apps/xwiki"

if [ ! -d "$BASE_DIR" ]; then
    mkdir -p $BASE_DIR
fi

DATA_DIR="$BASE_DIR/data"
if [ ! -d "$DATA_DIR" ]; then
    mkdir -p $DATA_DIR
fi

CONF_DIR="$BASE_DIR/conf"
if [ ! -d "$CONF_DIR" ]; then
    mkdir -p $CONF_DIR
fi

XWIKI_CONF_DIR="$CONF_DIR/xwiki"
if [ ! -d "$XWIKI_CONF_DIR" ]; then
    mkdir -p $XWIKI_CONF_DIR
fi

curl -fSLs https://raw.githubusercontent.com/xwiki-contrib/docker-xwiki/master/12/mysql-tomcat/mysql/xwiki.cnf -o "$XWIKI_CONF_DIR"/xwiki.cnf
curl -fSLs https://raw.githubusercontent.com/xwiki-contrib/docker-xwiki/master/12/mysql-tomcat/mysql/init.sql -o "$XWIKI_CONF_DIR"/init.sql